import { createFileRoute } from "@tanstack/react-router";
import { useMemo, useState, type FormEvent } from "react";
import {
  ArrowRight, Bot, Box, Check, ChevronDown, CircuitBoard, Cpu, FileText, Gauge,
  Menu, MessageSquare, Move3d, Search, Settings2, ShieldCheck, Sparkles, X, Zap,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { categories, productFamilies, products, searchItems, type Product } from "@/data/robotics";
import heroImage from "@/assets/robotics-hero.jpg";
import componentsImage from "@/assets/robotic-components.jpg";
import armImage from "@/assets/robotic-arm-cell.jpg";
import mobileImage from "@/assets/mobile-robotics.jpg";

export const Route = createFileRoute("/")({
  head: () => ({ meta: [
    { title: "Industrial Robotics, Motion & Automation Technology" },
    { name: "description", content: "Discover robotic components, precision motion, control systems, and automation technology engineered for industrial performance." },
    { property: "og:title", content: "Industrial Robotics, Motion & Automation Technology" },
    { property: "og:description", content: "Precision robotic components and intelligent automation for modern industry." },
    { property: "og:type", content: "website" },
    { name: "twitter:card", content: "summary_large_image" },
  ]}),
  component: HomePage,
});

type ModalType = "quote" | "engineer" | "search" | null;
const images = { components: componentsImage, arm: armImage, mobile: mobileImage };
const applications = [
  ["Automotive", "Assembly, welding, material handling, painting, and inspection.", armImage],
  ["Electronics", "Precision assembly, component handling, testing, and inspection.", armImage],
  ["Manufacturing", "Machine tending, assembly, and connected production automation.", componentsImage],
  ["Warehousing", "Picking, sorting, transportation, and storage automation.", mobileImage],
  ["Logistics", "AGVs, AMRs, and autonomous material movement.", mobileImage],
  ["Food & Packaging", "Hygienic handling, sorting, packaging, and palletizing.", armImage],
] as const;

function Brand() {
  return <a href="#top" className="flex items-center gap-3" aria-label="Axis robotics home"><span className="grid size-9 place-items-center border border-signal text-signal"><Move3d size={20} /></span><span><b className="block font-display text-xl leading-none tracking-wide">AXIS/01</b><span className="text-[9px] font-bold uppercase tracking-[.22em] text-muted-foreground">Robotics Engineering</span></span></a>;
}

function Header({ openModal }: { openModal: (type: ModalType) => void }) {
  const [menuOpen, setMenuOpen] = useState(false);
  const [productsOpen, setProductsOpen] = useState(false);
  const nav = ["Solutions", "Applications", "Technology", "Resources", "About", "Contact"];
  return <header className="fixed inset-x-0 top-0 z-40 border-b border-border/30 bg-surface-dark/90 text-surface-foreground backdrop-blur-xl">
    <div className="mx-auto flex h-20 max-w-[1440px] items-center justify-between px-5 lg:px-10">
      <Brand />
      <nav className="hidden items-center gap-7 lg:flex" aria-label="Main navigation">
        <button className="flex items-center gap-1 text-xs font-bold uppercase tracking-wider hover:text-signal" onClick={() => setProductsOpen(!productsOpen)} aria-expanded={productsOpen}>Products <ChevronDown size={14}/></button>
        {nav.map((item) => <a key={item} href={`#${item.toLowerCase()}`} className="text-xs font-bold uppercase tracking-wider text-surface-foreground/75 transition-colors hover:text-signal">{item}</a>)}
      </nav>
      <div className="flex items-center gap-2">
        <Button variant="ghost" size="icon" className="text-surface-foreground hover:bg-surface-elevated hover:text-signal" onClick={() => openModal("search")} aria-label="Search"><Search /></Button>
        <Button className="hidden h-11 rounded-none bg-signal px-5 font-bold uppercase text-signal-foreground hover:bg-signal/90 sm:inline-flex" onClick={() => openModal("quote")}>Request a quote <ArrowRight /></Button>
        <Button variant="ghost" size="icon" className="text-surface-foreground hover:bg-surface-elevated lg:hidden" onClick={() => setMenuOpen(!menuOpen)} aria-label="Open menu">{menuOpen ? <X/> : <Menu/>}</Button>
      </div>
    </div>
    {productsOpen && <div className="absolute inset-x-0 top-20 hidden border-b border-border/30 bg-surface-dark shadow-2xl lg:block">
      <div className="mx-auto grid max-w-[1440px] grid-cols-6 gap-8 px-10 py-9">{categories.map((category) => <div key={category.title}><p className="mb-4 font-display text-lg uppercase text-signal">{category.title}</p><ul className="space-y-2">{category.items.map(item => <li key={item}><a href="#products" onClick={() => setProductsOpen(false)} className="text-xs text-surface-foreground/65 hover:text-surface-foreground">{item}</a></li>)}</ul></div>)}</div>
      <a href="#products" onClick={() => setProductsOpen(false)} className="block border-t border-border/20 px-10 py-4 text-right text-xs font-bold uppercase tracking-widest text-signal">View all products →</a>
    </div>}
    {menuOpen && <nav className="border-t border-border/30 bg-surface-dark px-5 py-5 lg:hidden" aria-label="Mobile navigation">{["Products", ...nav].map(item => <a key={item} href={`#${item.toLowerCase()}`} onClick={() => setMenuOpen(false)} className="block border-b border-border/20 py-3 text-sm font-bold uppercase">{item}</a>)}<Button className="mt-5 w-full rounded-none" onClick={() => openModal("quote")}>Request a quote</Button></nav>}
  </header>;
}

function SectionHeading({ eyebrow, title, text, dark=false }: { eyebrow: string; title: string; text?: string; dark?: boolean }) {
  return <div className="mb-10 max-w-3xl"><p className="mb-4 text-xs font-bold uppercase tracking-[.22em] text-signal">{eyebrow}</p><h2 className={`font-display text-4xl font-bold uppercase leading-[.95] sm:text-5xl lg:text-6xl ${dark ? "text-surface-foreground" : "text-foreground"}`}>{title}</h2>{text && <p className={`mt-5 max-w-2xl leading-7 ${dark ? "text-surface-foreground/60" : "text-muted-foreground"}`}>{text}</p>}</div>;
}

function ProductFinder({ openModal }: { openModal: (type: ModalType) => void }) {
  const [category, setCategory] = useState("All");
  const [application, setApplication] = useState("All");
  const [requirement, setRequirement] = useState("All");
  const matched = useMemo(() => products.filter(p => (category === "All" || p.category === category) && (application === "All" || p.applications.includes(application)) && (requirement === "All" || p.requirements.includes(requirement))), [category, application, requirement]);
  const Filter = ({ label, value, options, set }: { label: string; value: string; options: string[]; set: (v:string)=>void }) => <label className="block"><span className="mb-2 block text-[10px] font-bold uppercase tracking-[.2em] text-muted-foreground">{label}</span><select value={value} onChange={e => set(e.target.value)} className="h-12 w-full border border-input bg-card px-3 text-sm focus:border-signal"><option>All</option>{options.map(x => <option key={x}>{x}</option>)}</select></label>;
  return <section id="finder" className="bg-background px-5 py-20 lg:px-10 lg:py-28"><div className="mx-auto max-w-[1360px]"><SectionHeading eyebrow="Product finder" title="Find the right technology for your application" text="Filter sample product concepts by system, task, and engineering priority. Final selection should be reviewed with an application engineer."/>
    <div className="grid gap-4 border-y border-border py-6 md:grid-cols-3"><Filter label="Product" value={category} options={[...new Set(products.map(p=>p.category))]} set={setCategory}/><Filter label="Application" value={application} options={["Assembly","Welding","Material Handling","Inspection","Pick & Place","Mobile Robotics"]} set={setApplication}/><Filter label="Requirement" value={requirement} options={["High Torque","High Speed","High Precision","High Payload","Compact Design"]} set={setRequirement}/></div>
    <div className="mt-8 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{matched.length ? matched.map(product => <ProductResult key={product.id} product={product} openModal={openModal}/>) : <div className="col-span-full border border-border bg-card p-10 text-center"><p className="font-display text-2xl uppercase">No exact sample match</p><p className="mt-2 text-sm text-muted-foreground">Talk to an engineer for a configured recommendation.</p><Button className="mt-5 rounded-none" onClick={()=>openModal("engineer")}>Talk to an engineer</Button></div>}</div>
  </div></section>;
}

function ProductResult({ product, openModal }: { product: Product; openModal: (type: ModalType)=>void }) {
  return <article className="group border border-border bg-card"><div className="aspect-[16/9] overflow-hidden bg-muted"><img src={images[product.image]} alt={`${product.name} sample product concept`} loading="lazy" width={1200} height={912} className="h-full w-full object-cover grayscale transition duration-500 group-hover:scale-[1.03] group-hover:grayscale-0"/></div><div className="p-6"><p className="text-[10px] font-bold uppercase tracking-[.2em] text-signal">{product.category} · Sample data</p><h3 className="mt-2 font-display text-2xl uppercase">{product.name}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{product.description}</p><div className="my-5 flex flex-wrap gap-2">{product.specs.map(s=><span key={s} className="border border-border px-2 py-1 text-[10px] uppercase text-muted-foreground">{s}</span>)}</div><div className="flex gap-2"><Button variant="outline" className="flex-1 rounded-none">View product</Button><Button className="flex-1 rounded-none" onClick={()=>openModal("quote")}>Request quote</Button></div></div></article>;
}

function ModalForms({ type, setType }: { type: ModalType; setType: (type: ModalType)=>void }) {
  const [success, setSuccess] = useState(false);
  const [query, setQuery] = useState("");
  const submit = (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); setSuccess(true); };
  const close = () => { setType(null); setSuccess(false); };
  if (type === "search") return <Dialog open onOpenChange={close}><DialogContent className="max-w-2xl rounded-none"><DialogHeader><DialogTitle className="font-display text-3xl uppercase">Search robotics technology</DialogTitle><DialogDescription>Search products, applications, specifications, articles, FAQs, and resources.</DialogDescription></DialogHeader><div className="relative"><Search className="absolute left-3 top-3 text-muted-foreground" size={18}/><Input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Try “6 axis” or “high torque”" className="h-12 rounded-none pl-10"/></div><div className="max-h-80 divide-y overflow-auto">{searchItems.filter(i => !query || `${i.title} ${i.type} ${i.detail}`.toLowerCase().includes(query.toLowerCase())).map(i=><button key={i.title} onClick={close} className="flex w-full items-center justify-between py-4 text-left hover:text-signal"><span><b className="block text-sm">{i.title}</b><small className="text-muted-foreground">{i.detail}</small></span><span className="text-[10px] uppercase tracking-wider text-muted-foreground">{i.type}</span></button>)}</div></DialogContent></Dialog>;
  return <Dialog open={Boolean(type)} onOpenChange={close}><DialogContent className="max-h-[90vh] overflow-y-auto rounded-none sm:max-w-xl"><DialogHeader><DialogTitle className="font-display text-3xl uppercase">{type === "quote" ? "Request a quote" : "Talk to an automation expert"}</DialogTitle><DialogDescription>{type === "quote" ? "Share your requirements and our team will review the application." : "Tell us about your technical challenge. We’ll follow up to discuss the right path."}</DialogDescription></DialogHeader>{success ? <div className="py-12 text-center"><span className="mx-auto grid size-14 place-items-center bg-signal text-signal-foreground"><Check/></span><h3 className="mt-6 font-display text-3xl uppercase">{type === "quote" ? "Request received" : "Message received"}</h3><p className="mt-3 text-sm text-muted-foreground">Thank you. Your requirement has been submitted successfully. Our team will review the details and contact you.</p><Button className="mt-6 rounded-none" onClick={close}>Close</Button></div> : <form onSubmit={submit} className="grid gap-4 sm:grid-cols-2"><Field label="Name*" name="name" required/><Field label="Company*" name="company" required/><Field label="Business email*" name="email" type="email" required/><Field label="Phone" name="phone" type="tel" pattern="[+0-9 ()-]{7,}"/><Field label={type === "quote" ? "Product" : "Industry"} name="product"/><Field label={type === "quote" ? "Quantity" : "Application"} name="application"/><label className="sm:col-span-2 text-xs font-bold uppercase tracking-wider">Technical requirement*<Textarea required className="mt-2 min-h-28 rounded-none"/></label><label className="sm:col-span-2 text-xs font-bold uppercase tracking-wider">Reference file <Input type="file" accept=".pdf,.doc,.docx,.png,.jpg,.jpeg" className="mt-2 h-12 rounded-none file:mr-3"/></label><Button type="submit" className="h-12 rounded-none sm:col-span-2">{type === "quote" ? "Submit quote request" : "Connect with an expert"}<ArrowRight/></Button></form>}</DialogContent></Dialog>;
}
function Field({label,...props}: {label:string; name:string; type?:string; required?:boolean; pattern?:string}) { return <label className="text-xs font-bold uppercase tracking-wider">{label}<Input {...props} className="mt-2 h-12 rounded-none"/></label>; }

function Chatbot({ openModal }: { openModal:(type:ModalType)=>void }) {
  const [open, setOpen] = useState(false); const [step, setStep] = useState(0); const [answers, setAnswers] = useState<string[]>([]);
  const options = step===0 ? ["Find a Product","Compare Products","Technical Information","Request a Quote","Talk to an Engineer"] : step===1 ? ["Robotic Arm","AGV / AMR","Industrial Machine","Automated Production Line","Other"] : step===2 ? ["Rotary","Linear","Mobile","Multi-axis"] : ["Torque","Speed","Precision","Payload","Compact Size"];
  const choose=(value:string)=>{ if(value==="Request a Quote") return openModal("quote"); if(value==="Talk to an Engineer") return openModal("engineer"); if(step===0 && value!=="Find a Product") return setStep(4); setAnswers([...answers,value]); setStep(step+1); };
  return <><button onClick={()=>setOpen(!open)} className="fixed bottom-20 right-4 z-40 flex h-12 items-center gap-2 bg-signal px-4 text-sm font-bold text-signal-foreground shadow-xl transition-transform hover:-translate-y-1 md:bottom-6 md:right-6" aria-label="Open Robotics Assistant"><Bot size={19}/><span className="hidden sm:inline">Robotics Assistant</span></button>{open&&<aside className="fixed bottom-36 right-4 z-40 w-[calc(100%-2rem)] max-w-sm border border-border bg-card shadow-2xl md:bottom-20 md:right-6" aria-label="Robotics Assistant"><div className="flex items-center justify-between bg-surface-dark p-4 text-surface-foreground"><span className="flex items-center gap-2 font-display text-lg uppercase"><Bot className="text-signal"/>Robotics Assistant</span><Button size="icon" variant="ghost" onClick={()=>setOpen(false)} className="text-surface-foreground"><X/></Button></div><div className="max-h-[60vh] overflow-y-auto p-5"><p className="text-sm leading-6 text-muted-foreground">{step===0 ? "Hello! I can help you find products, explore applications, understand technical information, or connect you with an engineer." : step===1 ? "What are you building?" : step===2 ? "What type of movement do you need?" : step===3 ? "What matters most?" : "Based on your answers, a configured motion solution may fit. Final requirements should be reviewed by an engineer."}</p>{step<4 ? <div className="mt-4 grid gap-2">{options.map(o=><Button key={o} variant="outline" className="h-auto justify-between rounded-none py-3 text-left whitespace-normal" onClick={()=>choose(o)}>{o}<ArrowRight/></Button>)}</div> : <div className="mt-5 border border-border p-4"><p className="text-[10px] uppercase tracking-widest text-signal">Suggested path</p><h4 className="mt-2 font-display text-xl uppercase">Integrated motion platform</h4><p className="mt-2 text-xs text-muted-foreground">A combination of actuator, precision reducer, controller, and feedback selected around your load profile.</p><div className="mt-4 flex gap-2"><Button className="rounded-none" onClick={()=>openModal("engineer")}>Expert review</Button><Button variant="outline" className="rounded-none" onClick={()=>{setStep(0);setAnswers([])}}>Restart</Button></div></div>}</div></aside>}</>;
}

function HomePage() {
  const [modal, setModal] = useState<ModalType>(null);
  return <div id="top" className="min-h-screen overflow-x-hidden"><Header openModal={setModal}/><main>
    <section className="relative flex min-h-[760px] items-end overflow-hidden bg-surface-dark pt-20 text-surface-foreground lg:min-h-[860px]"><img src={heroImage} alt="Industrial robotic arm operating in a precision manufacturing cell" width={1600} height={1008} fetchPriority="high" className="absolute inset-0 h-full w-full object-cover object-[68%_center]"/><div className="absolute inset-0 bg-[linear-gradient(90deg,var(--color-surface-dark)_0%,color-mix(in_oklab,var(--color-surface-dark)_92%,transparent)_38%,color-mix(in_oklab,var(--color-surface-dark)_25%,transparent)_72%,color-mix(in_oklab,var(--color-surface-dark)_60%,transparent)_100%)]"/><div className="technical-grid absolute inset-0 opacity-30"/><div className="relative mx-auto w-full max-w-[1440px] px-5 pb-16 lg:px-10 lg:pb-24"><div className="max-w-3xl"><p className="animate-rise text-xs font-bold uppercase tracking-[.24em] text-signal">Industrial robotics • Motion • Control</p><h1 className="animate-rise-delay mt-6 font-display text-6xl font-bold uppercase leading-[.85] sm:text-7xl lg:text-[104px]">Powering the future of industrial robotics</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-surface-foreground/75">Advanced robotic components, motion technologies, and control systems engineered for precise, reliable, and intelligent automation.</p><div className="mt-9 flex flex-wrap gap-3"><Button asChild className="h-13 rounded-none px-7 text-xs font-bold uppercase"><a href="#products">Explore products <ArrowRight/></a></Button><Button variant="outline" className="h-13 rounded-none border-surface-foreground/35 bg-transparent px-7 text-xs font-bold uppercase text-surface-foreground hover:bg-surface-foreground hover:text-surface-dark" onClick={()=>setModal("engineer")}>Talk to an engineer</Button></div><p className="mt-10 text-[10px] font-bold uppercase tracking-[.2em] text-surface-foreground/50">Precision motion · Intelligent control · Industrial performance</p></div></div></section>

    <section className="border-b border-border bg-card"><div className="mx-auto grid max-w-[1440px] sm:grid-cols-2 lg:grid-cols-4">{[
      { icon: Gauge, title: "Precision", text: "Accurate and repeatable robotic movement." },
      { icon: ShieldCheck, title: "Reliability", text: "Designed for demanding industrial environments." },
      { icon: CircuitBoard, title: "Integration", text: "Components designed to work within complete systems." },
      { icon: Settings2, title: "Scalability", text: "From components to complete automation solutions." },
    ].map(({icon: Icon,title,text},i)=><div key={title} className={`p-6 lg:p-8 ${i<3?"border-b sm:border-r lg:border-b-0":""}`}><Icon className="mb-5 text-signal" size={23}/><h2 className="font-display text-xl uppercase">{title}</h2><p className="mt-2 text-xs leading-5 text-muted-foreground">{text}</p></div>)}</div></section>

    <section id="products" className="px-5 py-20 lg:px-10 lg:py-28"><div className="mx-auto max-w-[1360px]"><SectionHeading eyebrow="Our portfolio" title="Explore our robotics technology" text="Discover the technologies behind modern robotic systems — from individual motion components to complete industrial automation platforms."/><div className="grid border-l border-t border-border md:grid-cols-2 lg:grid-cols-3">{productFamilies.map(([title,subtitle,text],i)=><article key={title} className="group relative min-h-72 border-b border-r border-border bg-card p-7 transition-colors hover:bg-surface-dark hover:text-surface-foreground"><span className="text-[10px] font-bold text-muted-foreground">0{i+1}</span>{[Zap,Settings2,Move3d,Bot,Box,Cpu].map((Icon,j)=>j===i?<Icon key={j} className="absolute right-7 top-7 text-signal"/>:null)}<div className="mt-16"><h3 className="font-display text-3xl uppercase">{title}</h3><p className="mt-2 text-sm font-semibold">{subtitle}</p><p className="mt-3 text-xs leading-5 text-muted-foreground">{text}</p><a href="#finder" className="mt-6 inline-flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-signal">Explore <ArrowRight size={14}/></a></div></article>)}</div></div></section>

    <ProductFinder openModal={setModal}/>

    <section id="technology" className="technical-grid bg-surface-dark px-5 py-20 text-surface-foreground lg:px-10 lg:py-28"><div className="mx-auto max-w-[1360px]"><SectionHeading dark eyebrow="Robotics ecosystem" title="One ecosystem. Every movement." text="A modern robot is an interconnected system of power, motion, control, sensing, and intelligence."/><div className="grid items-center gap-3 lg:grid-cols-[1fr_auto_1fr_auto_1fr_auto_1fr_auto_1fr]">{[
      { icon: Zap, title: "Power", text: "Motors & drives" },
      { icon: Move3d, title: "Motion", text: "Actuators & reducers" },
      { icon: Cpu, title: "Control", text: "Controllers & motion" },
      { icon: Gauge, title: "Feedback", text: "Sensors & monitoring" },
      { icon: Bot, title: "Automation", text: "Robotic systems" },
    ].map(({icon: Icon,title,text},i)=><div className="contents" key={title}><div className="border border-surface-foreground/15 bg-surface-elevated p-5"><Icon className="text-signal"/><p className="mt-8 font-display text-2xl uppercase">{title}</p><p className="mt-1 text-xs text-surface-foreground/50">{text}</p></div>{i<4&&<div className="hidden items-center lg:flex"><div className="signal-line h-px w-8"/><ArrowRight size={14} className="text-signal"/></div>}</div>)}</div></div></section>

    <section id="applications" className="bg-card px-5 py-20 lg:px-10 lg:py-28"><div className="mx-auto max-w-[1360px]"><SectionHeading eyebrow="Applications" title="Built for the real world" text="Robotics technologies designed around real industrial requirements."/><div className="grid gap-px bg-border md:grid-cols-2 lg:grid-cols-3">{applications.map(([title,text,img])=><article key={title} className="group relative aspect-[4/3] overflow-hidden bg-surface-dark"><img src={img} alt={`${title} industrial robotics application`} loading="lazy" width={1200} height={912} className="h-full w-full object-cover opacity-70 grayscale transition duration-500 group-hover:scale-105 group-hover:opacity-50"/><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-surface-dark to-transparent p-7 pt-24 text-surface-foreground"><h3 className="font-display text-3xl uppercase">{title}</h3><p className="mt-2 text-xs text-surface-foreground/65">{text}</p><span className="mt-4 flex items-center gap-2 text-xs font-bold uppercase text-signal">Explore <ArrowRight size={14}/></span></div></article>)}</div></div></section>

    <section className="px-5 py-20 lg:px-10 lg:py-28"><div className="mx-auto grid max-w-[1360px] gap-14 lg:grid-cols-[.75fr_1.25fr]"><SectionHeading eyebrow="Technology stack" title="From motion to intelligence" text="Mechanical design, electrical power, real-time control, sensing, software, and intelligence working as one engineered architecture."/><div className="space-y-2">{[["Mechanical","Actuators · Reducers · Gears · Joints · Wheels"],["Electrical","Motors · Drives · Power systems"],["Control","Controllers · PLCs · Servo systems"],["Sensing","Position · Force · Vision · Proximity"],["Software","Programming · Monitoring · Analytics"],["Intelligence","AI · Machine learning · Autonomous systems"]].map(([a,b],i)=><div key={a} className="group grid grid-cols-[48px_1fr] items-center border border-border bg-card transition hover:border-signal"><span className="grid h-full place-items-center border-r border-border font-display text-lg text-muted-foreground">0{i+1}</span><div className="p-5"><h3 className="font-display text-2xl uppercase">{a}</h3><p className="text-xs text-muted-foreground">{b}</p></div></div>)}</div></div></section>

    <section id="solutions" className="bg-surface-dark px-5 py-20 text-surface-foreground lg:px-10 lg:py-28"><div className="mx-auto max-w-[1360px]"><SectionHeading dark eyebrow="Industry 4.0" title="Connecting robotics with the intelligent factory" text="Connected robots communicate with sensors, controllers, industrial software, and data platforms to create smarter production environments."/><div className="flex flex-wrap items-center justify-center gap-2 py-8">{["Robot","Sensor","Controller","Edge","Cloud","Analytics"].map((x,i)=><div className="contents" key={x}><span className="border border-surface-foreground/20 bg-surface-elevated px-5 py-4 font-display text-xl uppercase">{x}</span>{i<5&&<ArrowRight className="text-signal"/>}</div>)}</div><div className="mt-6 flex flex-wrap justify-center gap-2">{["Industrial IoT","PLC","SCADA","MES","Edge Computing","Cloud","AI Analytics"].map(x=><span key={x} className="border border-surface-foreground/15 px-3 py-2 text-[10px] uppercase tracking-widest text-surface-foreground/55">{x}</span>)}</div></div></section>

    <section id="resources" className="bg-card px-5 py-20 lg:px-10 lg:py-28"><div className="mx-auto max-w-[1360px]"><SectionHeading eyebrow="Knowledge center" title="Engineering resources" text="Everything engineers need to evaluate, design, integrate, and deploy robotic systems."/><div className="grid border-l border-t border-border md:grid-cols-2 lg:grid-cols-3">{[["Product Catalogues","Browse the robotics portfolio."],["Datasheets","Access technical specifications."],["Application Notes","Understand practical implementation."],["Case Studies","Explore real-world automation applications."],["Technical Articles","Learn about robotics and automation."],["FAQs","Find answers to common technical questions."]].map(([t,d])=><a key={t} href="#contact" className="group border-b border-r border-border p-6 hover:bg-muted"><FileText className="text-signal"/><h3 className="mt-10 font-display text-2xl uppercase">{t}</h3><p className="mt-2 text-sm text-muted-foreground">{d}</p><ArrowRight className="mt-5 transition-transform group-hover:translate-x-2" size={18}/></a>)}</div></div></section>

    <section id="contact" className="bg-signal px-5 py-20 text-signal-foreground lg:px-10 lg:py-28"><div className="mx-auto flex max-w-[1360px] flex-col justify-between gap-8 lg:flex-row lg:items-end"><div className="max-w-4xl"><p className="text-xs font-bold uppercase tracking-[.2em]">Engineering support</p><h2 className="mt-4 font-display text-5xl font-bold uppercase leading-[.9] sm:text-7xl">Ready to build your next robotic system?</h2><p className="mt-6 max-w-2xl leading-7">Whether you're selecting a component, developing a robotic machine, or planning a complete automation system, we're here to help.</p></div><div className="flex flex-wrap gap-3"><Button variant="outline" className="h-12 rounded-none border-signal-foreground bg-transparent text-signal-foreground hover:bg-signal-foreground hover:text-signal" onClick={()=>setModal("engineer")}>Talk to an engineer</Button><Button className="h-12 rounded-none bg-surface-dark text-surface-foreground hover:bg-surface-elevated" onClick={()=>setModal("quote")}>Request a quote <ArrowRight/></Button></div></div></section>
  </main><Footer/><Chatbot openModal={setModal}/><ModalForms type={modal} setType={setModal}/><Button className="fixed inset-x-0 bottom-0 z-30 h-14 rounded-none md:hidden" onClick={()=>setModal("quote")}>Request quote <ArrowRight/></Button></div>;
}

function Footer(){return <footer id="about" className="bg-surface-dark px-5 pb-24 pt-16 text-surface-foreground md:pb-8 lg:px-10"><div className="mx-auto max-w-[1360px]"><div className="grid gap-10 border-b border-surface-foreground/15 pb-12 sm:grid-cols-2 lg:grid-cols-5"><div><Brand/><p className="mt-5 max-w-xs text-xs leading-5 text-surface-foreground/50">Robotic components, motion control, and automation technologies for modern industry.</p></div>{[["Products","Actuators","Precision Reducers","Robotic Wheels","Robotic Arms","Industrial Robots","Control Systems"],["Solutions","Factory Automation","Motion Control","Mobile Robotics","Smart Manufacturing","Material Handling"],["Applications","Automotive","Electronics","Manufacturing","Warehousing","Logistics","Packaging"],["Resources","Product Catalogue","Datasheets","Technical Documentation","Case Studies","Technical Articles","FAQs"]].map(([h,...items])=><div key={h}><h3 className="font-display text-lg uppercase text-signal">{h}</h3><ul className="mt-4 space-y-2">{items.map(x=><li key={x}><a href="#products" className="text-xs text-surface-foreground/50 hover:text-surface-foreground">{x}</a></li>)}</ul></div>)}</div><div className="flex flex-col justify-between gap-4 pt-6 text-[10px] uppercase tracking-wider text-surface-foreground/40 sm:flex-row"><span>© 2026 AXIS/01 Robotics Engineering</span><span>Privacy Policy · Terms · Cookie Policy</span></div></div></footer>}
